services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WechatWorkStaffBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']

    # 测试环境使用 MockWorkService
    WechatWorkBundle\Service\WorkServiceInterface:
        class: WechatWorkStaffBundle\MockObject\MockWorkService
        public: true

    # 直接覆盖具体的 WorkService 类
    WechatWorkBundle\Service\WorkService:
        class: WechatWorkStaffBundle\MockObject\MockWorkService
        public: true